GREEK_TO_LAT = {
    "α":"alp",
    "β":"bet",
    "γ":"gam",
    "δ":"del",
    "ε":"eps",
    "ζ":"zet",
    "η":"eta",
    "θ":"the",
    "ι":"iot",
    "κ":"kap",
    "λ":"lam",
    "μ":"mu",
    "ν":"nu",
    "ξ":"xi",
    "ο":"omi",
    "π":"pi",
    "ρ":"rho",
    "σ":"sig",
    "ς":"sig",
    "τ":"tau",
    "υ":"ups",
    "φ":"phi",
    "χ":"chi",
    "ψ":"psi",
    "ω":"ome"
}

SHORT_LAT_TO_GREEK = {
    "alp":"α",
    "bet":"β",
    "gam":"γ",
    "del":"δ",
    "eps":"ε",
    "zet":"ζ",
    "eta":"η",
    "the":"θ",
    "iot":"ι",
    "kap":"κ",
    "lam":"λ",
    "mu":"μ",
    "nu":"ν",
    "xi":"ξ",
    "omi":"ο",
    "pi":"π",
    "rho":"ρ",
    "sig":"σ",
    "tau":"τ",
    "ups":"υ",
    "phi":"φ",
    "chi":"χ",
    "psi":"ψ",
    "ome":"ω",
}

LONG_LAT_TO_GREEK = {
    "alpha":"α",
    "beta":"β",
    "gamma":"γ",
    "delta":"δ",
    "epsilon":"ε",
    "zeta":"ζ",
    "eta":"η",
    "theta":"θ",
    "iota":"ι",
    "kappa":"κ",
    "lamda":"λ",
    "mu":"μ",
    "nu":"ν",
    "xi":"ξ",
    "omicron":"ο",
    "pi":"π",
    "rho":"ρ",
    "sigma":"σ",
    "tau":"τ",
    "upsilon":"υ",
    "phi":"φ",
    "chi":"χ",
    "psi":"ψ",
    "omega":"ω",
}

LONG_LAT_CZ_TO_GREEK = {
    "alfa":"α",
    "beta":"β",
    "gama":"γ",
    "delta":"δ",
    "epsilon":"ε",
    "zeta":"ζ",
    "eta":"η",
    "theta":"θ",
    "iota":"ι",
    "kappa":"κ",
    "lamda":"λ",
    "mi":"μ",
    "ny":"ν",
    "ksi":"ξ",
    "omikron":"ο",
    "pi":"π",
    "ro":"ρ",
    "sigma":"σ",
    "tau":"τ",
    "ypsilon":"υ",
    "fi":"φ",
    "chi":"χ",
    "psi":"ψ",
    "omega":"ω",
}

SHORT_LAT_TO_GREEK_EXT = {
    "alp": "α",
     "alp 1": "α²",
     "alp 2": "α¹",

    "bet": "β",
    "bet 1": "β¹",
    "bet 2": "β²",
    "bet 3": "β³",

    "gam": "γ",
    "gam 1": "γ¹",
    "gam 2": "γ²",
    "gam 3": "γ³",

    "del": "δ",
    "del 1": "δ¹",
    "del 2": "δ²",
    "del 3": "δ³",

    "eps": "ε",
    "eps 1": "ε¹",
    "eps 2": "ε²",

    "zet": "ζ",
    "zet 1": "ζ¹",
    "zet 2": "ζ²",
    "zet 3": "ζ³",
    "zet 4": "ζ⁴",

    "eta": "η",
    "eta 1": "η¹",
    "eta 2": "η²",
    "eta 3": "η³",

    "the": "θ",
    "the 1": "θ¹",
    "the 2": "θ²",

    "iot": "ι",
    "iot 1": "ι¹",
    "iot 2": "ι²",

    "kap": "κ",
    "kap 1": "κ¹",
    "kap 2": "κ²",

    "lam": "λ",
    "lam 1": "λ¹",
    "lam 2": "λ²",

    "mu": "μ",
    "mu 1": "μ¹",
    "mu 2": "μ²",

    "nu": "ν",
    "nu 1": "ν¹",
    "nu 2": "ν²",
    "nu 3": "ν³",

    "xi": "ξ",
    "xi 1": "ξ¹",
    "xi 2": "ξ²",

    "omi": "ο",
    "omi 1": "ο¹",
    "omi 2": "ο²",

    "pi": "π",
    "pi 1": "π¹",
    "pi 2": "π²",
    "pi 3": "π³",
    "pi 4": "π⁴",
    "pi 5": "π⁵",
    "pi 6": "π⁶",

    "rho": "ρ",
    "rho 1": "ρ¹",
    "rho 2": "ρ²",
    "rho 3": "ρ³",

    "sig": "σ",
    "sig 1": "σ¹",
    "sig 2": "σ²",
    "sig 3": "σ³",

    "sig": "ς",

    "tau": "τ",
    "tau 1": "τ¹",
    "tau 2": "τ²",
    "tau 3": "τ³",
    "tau 4": "τ⁴",
    "tau 5": "τ⁵",
    "tau 6": "τ⁶",
    "tau 7": "τ⁷",
    "tau 8": "τ⁸",
    "tau 9": "τ⁹",

    "ups": "υ",
    "ups 1": "υ¹",
    "ups 2": "υ²",
    "ups 3": "υ⁴",

    "phi": "φ",
    "phi 1": "φ¹",
    "phi 2": "φ²",
    "phi 3": "φ³",
    "phi 4": "φ⁴",

    "chi": "χ",
    "chi 1": "χ¹",
    "chi 2": "χ²",
    "chi 3": "χ³",

    "psi": "ψ",
    "psi 1": "ψ¹",
    "psi 2": "ψ²",
    "psi 3": "ψ³",
    "psi 4": "ψ⁴",
    "psi 5": "ψ⁵",
    "psi 6": "ψ⁶",
    "psi 7": "ψ⁷",
    "psi 8": "ψ⁸",
    "psi 9": "ψ⁹",

    "ome": "ω",
    "ome 1": "ω¹",
    "ome 2": "ω²",
}

