"""show_minor_axis

Revision ID: 006cee50cac0
Revises: 3607840eb065
Create Date: 2020-09-28 17:54:51.260146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006cee50cac0'
down_revision = '3607840eb065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_minor_axis', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.drop_column('show_minor_axis')

    # ### end Alembic commands ###
