"""Not null in observations and plans

Revision ID: 016d52caf6cc
Revises: c3a46c617298
Create Date: 2021-11-07 20:12:11.440970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016d52caf6cc'
down_revision = 'c3a46c617298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.alter_column('is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
