"""Sky lists

Revision ID: 01a6a04187e8
Revises: e6185e73ade3
Create Date: 2020-02-09 19:09:39.851582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a6a04187e8'
down_revision = 'e6185e73ade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sky_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sky_lists_name'), 'sky_lists', ['name'], unique=False)
    op.create_table('sky_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sky_list_id', sa.Integer(), nullable=False),
    sa.Column('dso_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], ),
    sa.ForeignKeyConstraint(['sky_list_id'], ['sky_lists.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sky_list_item')
    op.drop_index('ix_sky_list_name', table_name='sky_list')
    op.drop_table('sky_list')
    op.drop_constraint(None, 'session_plans', type_='foreignkey')
    op.create_foreign_key(None, 'session_plans', 'sky_lists', ['sky_list_id'], ['id'])
    op.drop_constraint(None, 'wish_lists', type_='foreignkey')
    op.create_foreign_key(None, 'wish_lists', 'sky_lists', ['sky_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wish_lists', type_='foreignkey')
    op.create_foreign_key(None, 'wish_lists', 'sky_list', ['sky_list_id'], ['id'])
    op.drop_constraint(None, 'session_plans', type_='foreignkey')
    op.create_foreign_key(None, 'session_plans', 'sky_list', ['sky_list_id'], ['id'])
    op.create_table('sky_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('update_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sky_list_name', 'sky_list', ['name'], unique=False)
    op.create_table('sky_list_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sky_list_id', sa.INTEGER(), nullable=False),
    sa.Column('dso_id', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('update_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], ),
    sa.ForeignKeyConstraint(['sky_list_id'], ['sky_list.id'], ),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sky_list_items')
    op.drop_index(op.f('ix_sky_lists_name'), table_name='sky_lists')
    op.drop_table('sky_lists')
    # ### end Alembic commands ###
