"""DB Updates exclusion

Revision ID: 0818dbd968b3
Revises: 4f33ef5ae1e5
Create Date: 2022-10-29 19:33:58.295224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0818dbd968b3'
down_revision = '4f33ef5ae1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_updates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_updates'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_updates')
    # ### end Alembic commands ###
