"""comet.is_desintegrated

Revision ID: 0b1286010134
Revises: d08214aac36a
Create Date: 2024-11-19 21:16:11.499919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1286010134'
down_revision = 'd08214aac36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disintegrated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.drop_column('is_disintegrated')

    # ### end Alembic commands ###
