"""Planet moons

Revision ID: 0ca6794f5ed5
Revises: 380f0a73bbc7
Create Date: 2024-10-12 21:47:40.537224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca6794f5ed5'
down_revision = '380f0a73bbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_moons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('iau_number', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name=op.f('fk_planet_moons_planet_id_planets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planet_moons'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_moon_id', sa.Integer(), nullable=True))
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', 'PLANET', 'PLANET_MOON', name='observationtargettype'),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_observations_planet_moon_id_planet_moons'), 'planet_moons', ['planet_moon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_planet_moon_id_planet_moons'), type_='foreignkey')
        batch_op.alter_column('target_type',
               existing_type=sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', 'PLANET', 'PLANET_MOON', name='observationtargettype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('planet_moon_id')

    op.drop_table('planet_moons')
    # ### end Alembic commands ###
