"""Drop nullable constraints

Revision ID: 0e9cb1f10c33
Revises: ecbd06421e95
Create Date: 2022-04-05 19:42:49.907824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9cb1f10c33'
down_revision = 'ecbd06421e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.alter_column('focal_length_mm',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fov_deg',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.alter_column('magnification',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('magnification',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.alter_column('diameter_inch',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fov_deg',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('focal_length_mm',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
