"""Comets

Revision ID: 130e21bec8a9
Revises: b575afc826ce
Create Date: 2022-01-30 19:06:47.755317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130e21bec8a9'
down_revision = 'b575afc826ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comet_id', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('orbit_type', sa.String(length=2), nullable=True),
    sa.Column('designation_packed', sa.String(length=30), nullable=True),
    sa.Column('perihelion_year', sa.Integer(), nullable=True),
    sa.Column('perihelion_month', sa.Integer(), nullable=True),
    sa.Column('perihelion_day', sa.Float(), nullable=True),
    sa.Column('perihelion_distance_au', sa.Float(), nullable=True),
    sa.Column('eccentricity', sa.Float(), nullable=True),
    sa.Column('argument_of_perihelion_degrees', sa.Float(), nullable=True),
    sa.Column('longitude_of_ascending_node_degrees', sa.Float(), nullable=True),
    sa.Column('inclination_degrees', sa.Float(), nullable=True),
    sa.Column('perturbed_epoch_year', sa.Float(), nullable=True),
    sa.Column('perturbed_epoch_month', sa.Float(), nullable=True),
    sa.Column('perturbed_epoch_day', sa.Float(), nullable=True),
    sa.Column('magnitude_g', sa.Float(), nullable=True),
    sa.Column('magnitude_k', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comets'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comets')
    # ### end Alembic commands ###
