"""Doubles 2

Revision ID: 1416c260ee7e
Revises: e4af7a761f21
Create Date: 2022-01-15 12:11:22.162059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1416c260ee7e'
down_revision = 'e4af7a761f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_star_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('long_name', sa.String(length=256), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_lists_create_by_users')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_double_star_lists_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_lists'))
    )
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_star_lists_long_name'), ['long_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_double_star_lists_name'), ['name'], unique=False)

    op.create_table('double_star_list_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_star_list_id', sa.Integer(), nullable=False),
    sa.Column('long_name', sa.String(length=256), nullable=True),
    sa.Column('short_descr', sa.String(length=256), nullable=True),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_list_descriptions_create_by_users')),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name=op.f('fk_double_star_list_descriptions_double_star_list_id_double_star_lists')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_double_star_list_descriptions_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_list_descriptions'))
    )
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_star_list_descriptions_long_name'), ['long_name'], unique=False)

    op.create_table('double_star_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_star_list_id', sa.Integer(), nullable=False),
    sa.Column('star_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_list_items_create_by_users')),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name=op.f('fk_double_star_list_items_double_star_list_id_double_star_lists')),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name=op.f('fk_double_star_list_items_star_id_stars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_list_items'))
    )
    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.create_index('double_star_list_item_index', ['double_star_list_id', 'item_id'], unique=False)

    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta_mag', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.drop_column('delta_mag')

    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.drop_index('double_star_list_item_index')

    op.drop_table('double_star_list_items')
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_star_list_descriptions_long_name'))

    op.drop_table('double_star_list_descriptions')
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_star_lists_name'))
        batch_op.drop_index(batch_op.f('ix_double_star_lists_long_name'))

    op.drop_table('double_star_lists')
    # ### end Alembic commands ###
