"""Update dso list

Revision ID: 14de8764dfd1
Revises: 9421bf39225f
Create Date: 2020-09-28 08:35:48.069429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14de8764dfd1'
down_revision = '9421bf39225f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_angular_size', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_dso_type', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.drop_column('show_dso_type')
        batch_op.drop_column('show_angular_size')

    # ### end Alembic commands ###
