"""has_detail_view

Revision ID: 1859df95193b
Revises: 441f32a36c11
Create Date: 2023-10-29 16:36:54.905924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1859df95193b'
down_revision = '441f32a36c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_detail_view', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.drop_column('has_detail_view')

    # ### end Alembic commands ###
