"""Standalone observations

Revision ID: 19c33ee21175
Revises: f41cb289d440
Create Date: 2022-03-31 21:05:18.110093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c33ee21175'
down_revision = 'f41cb289d440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('faintest_star', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seeing', sa.Enum('TERRIBLE', 'VERYBAD', 'BAD', 'AVERAGE', 'GOOD', 'EXCELLENT', name='seeing'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('seeing')
        batch_op.drop_column('faintest_star')
        batch_op.drop_column('sqm')

    # ### end Alembic commands ###
