"""Archived plan

Revision ID: 1cc4ca5c52c0
Revises: dccf7f7d1c9b
Create Date: 2021-11-05 09:33:57.832853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc4ca5c52c0'
down_revision = 'dccf7f7d1c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
