"""Axis ratio

Revision ID: 23ada8e1fa92
Revises: d9babf3a822a
Create Date: 2022-08-13 18:26:25.640607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ada8e1fa92'
down_revision = 'd9babf3a822a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('axis_ratio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.drop_column('axis_ratio')

    # ### end Alembic commands ###
