"""Initial commit

Revision ID: 2559cd21e9dc
Revises: 
Create Date: 2022-01-02 20:08:57.836023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2559cd21e9dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deep_sky_objects', schema=None) as batch_op:
        batch_op.drop_index('ix_deep_sky_objects_name')

    op.drop_table('deep_sky_objects')
    op.drop_table('dso_catalogue_links')
    with op.batch_alter_table('obs_session_plan_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_observation_plan_runs_observation_id_observations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_obs_session_plan_runs_observing_session_id_observing_sessions'), 'observing_sessions', ['observing_session_id'], ['id'])

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_observation_items_observation_id_observations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_observations_observing_session_id_observing_sessions'), 'observing_sessions', ['observing_session_id'], ['id'])

    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_observations_date_from')
        batch_op.drop_index('ix_observations_date_to')
        batch_op.drop_index('ix_observations_location_id')
        batch_op.drop_index('ix_observations_title')
        batch_op.drop_index('ix_observations_user_id')
        batch_op.create_index(batch_op.f('ix_observing_sessions_date_from'), ['date_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_observing_sessions_date_to'), ['date_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_observing_sessions_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observing_sessions_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_observing_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sqm_full_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sqm_full_records_observation_id_observations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sqm_full_records_observing_session_id_observing_sessions'), 'observing_sessions', ['observing_session_id'], ['id'])

    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_index('ix_telescopes_model2')
        batch_op.drop_index('ix_telescopes_name2')
        batch_op.drop_index('ix_telescopes_user_id2')
        batch_op.drop_index('ix_telescopes_vendor2')
        batch_op.create_index(batch_op.f('ix_telescopes_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_telescopes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_telescopes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telescopes_vendor'), ['vendor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telescopes_vendor'))
        batch_op.drop_index(batch_op.f('ix_telescopes_user_id'))
        batch_op.drop_index(batch_op.f('ix_telescopes_name'))
        batch_op.drop_index(batch_op.f('ix_telescopes_model'))
        batch_op.create_index('ix_telescopes_vendor2', ['vendor'], unique=False)
        batch_op.create_index('ix_telescopes_user_id2', ['user_id'], unique=False)
        batch_op.create_index('ix_telescopes_name2', ['name'], unique=False)
        batch_op.create_index('ix_telescopes_model2', ['model'], unique=False)

    with op.batch_alter_table('sqm_full_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sqm_full_records_observing_session_id_observing_sessions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_sqm_full_records_observation_id_observations', 'observations', ['observing_session_id'], ['id'])

    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observing_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_observing_sessions_title'))
        batch_op.drop_index(batch_op.f('ix_observing_sessions_location_id'))
        batch_op.drop_index(batch_op.f('ix_observing_sessions_date_to'))
        batch_op.drop_index(batch_op.f('ix_observing_sessions_date_from'))
        batch_op.create_index('ix_observations_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_observations_title', ['title'], unique=False)
        batch_op.create_index('ix_observations_location_id', ['location_id'], unique=False)
        batch_op.create_index('ix_observations_date_to', ['date_to'], unique=False)
        batch_op.create_index('ix_observations_date_from', ['date_from'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_observing_session_id_observing_sessions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_observation_items_observation_id_observations', 'observations', ['observing_session_id'], ['id'])

    with op.batch_alter_table('obs_session_plan_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_obs_session_plan_runs_observing_session_id_observing_sessions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_observation_plan_runs_observation_id_observations', 'observations', ['observing_session_id'], ['id'])

    op.create_table('dso_catalogue_links',
    sa.Column('catalogue_id', sa.INTEGER(), nullable=False),
    sa.Column('dso_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.ForeignKeyConstraint(['dso_id'], ['deep_sky_objects.id'], ),
    sa.PrimaryKeyConstraint('catalogue_id', 'dso_id')
    )
    op.create_table('deep_sky_objects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('type', sa.VARCHAR(length=8), nullable=True),
    sa.Column('ra', sa.FLOAT(), nullable=True),
    sa.Column('dec', sa.FLOAT(), nullable=True),
    sa.Column('constellation_id', sa.INTEGER(), nullable=True),
    sa.Column('catalogue_id', sa.INTEGER(), nullable=True),
    sa.Column('major_axis', sa.FLOAT(), nullable=True),
    sa.Column('minor_axis', sa.FLOAT(), nullable=True),
    sa.Column('positon_angle', sa.FLOAT(), nullable=True),
    sa.Column('b_mag', sa.FLOAT(), nullable=True),
    sa.Column('v_mag', sa.FLOAT(), nullable=True),
    sa.Column('j_mag', sa.FLOAT(), nullable=True),
    sa.Column('h_mag', sa.FLOAT(), nullable=True),
    sa.Column('k_mag', sa.FLOAT(), nullable=True),
    sa.Column('surface_bright', sa.FLOAT(), nullable=True),
    sa.Column('hubble_type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('c_star_u_mag', sa.FLOAT(), nullable=True),
    sa.Column('c_star_b_mag', sa.FLOAT(), nullable=True),
    sa.Column('c_star_v_mag', sa.FLOAT(), nullable=True),
    sa.Column('identifiers', sa.TEXT(), nullable=True),
    sa.Column('common_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('descr', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['deep_sky_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_sky_objects', schema=None) as batch_op:
        batch_op.create_index('ix_deep_sky_objects_name', ['name'], unique=False)

    # ### end Alembic commands ###
