"""SQM3

Revision ID: 25a9ec3ca761
Revises: 563303b02f78
Create Date: 2020-03-05 19:30:06.749077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a9ec3ca761'
down_revision = '563303b02f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqm_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('sub_type', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sqm_devices'))
    )
    op.create_table('sqm_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sqm_device_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sqm_records'))
    )
    with op.batch_alter_table('sqm_records', schema=None) as batch_op:
        batch_op.create_index('sqm_record_index', ['sqm_device_id', 'date_time'], unique=False)

    op.create_table('sqm_full_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sqm_device_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weather', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_sqm_full_records_location_id_locations')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_sqm_full_records_observation_id_observations')),
    sa.ForeignKeyConstraint(['sqm_device_id'], ['sqm_devices.id'], name=op.f('fk_sqm_full_records_sqm_device_id_sqm_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sqm_full_records'))
    )
    op.create_table('sqm_full_record_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sqm_reading_id', sa.Integer(), nullable=False),
    sa.Column('sky_position', sa.Integer(), nullable=True),
    sa.Column('value_1', sa.Float(), nullable=True),
    sa.Column('value_2', sa.Float(), nullable=True),
    sa.Column('value_3', sa.Float(), nullable=True),
    sa.Column('value_4', sa.Float(), nullable=True),
    sa.Column('value_5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sqm_reading_id'], ['sqm_full_records.id'], name=op.f('fk_sqm_full_record_values_sqm_reading_id_sqm_full_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sqm_full_record_values'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqm_full_record_values')
    op.drop_table('sqm_full_records')
    with op.batch_alter_table('sqm_records', schema=None) as batch_op:
        batch_op.drop_index('sqm_record_index')

    op.drop_table('sqm_records')
    op.drop_table('sqm_devices')
    # ### end Alembic commands ###
