"""User object list

Revision ID: 26896e944ee7
Revises: a0dbbad0f04d
Create Date: 2025-04-08 22:11:07.081947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26896e944ee7'
down_revision = 'a0dbbad0f04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_object_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_object_lists_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_object_lists'))
    )
    with op.batch_alter_table('user_object_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_object_lists_title'), ['title'], unique=False)

    op.create_table('user_object_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_object_list_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', name='userobjectlistitemtype'), nullable=False),
    sa.Column('double_star_id', sa.Integer(), nullable=True),
    sa.Column('comet_id', sa.Integer(), nullable=True),
    sa.Column('minor_planet_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comet_id'], ['comets.id'], name=op.f('fk_user_object_list_items_comet_id_comets')),
    sa.ForeignKeyConstraint(['double_star_id'], ['double_stars.id'], name=op.f('fk_user_object_list_items_double_star_id_double_stars')),
    sa.ForeignKeyConstraint(['minor_planet_id'], ['minor_planets.id'], name=op.f('fk_user_object_list_items_minor_planet_id_minor_planets')),
    sa.ForeignKeyConstraint(['user_object_list_id'], ['user_object_lists.id'], name=op.f('fk_user_object_list_items_user_object_list_id_user_object_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_object_list_items'))
    )
    with op.batch_alter_table('user_object_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_object_list_items_user_object_list_id'), ['user_object_list_id'], unique=False)

    op.create_table('user_object_list_item_dsos',
    sa.Column('user_object_list_item_id', sa.Integer(), nullable=True),
    sa.Column('dso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name=op.f('fk_user_object_list_item_dsos_dso_id_deepsky_objects')),
    sa.ForeignKeyConstraint(['user_object_list_item_id'], ['user_object_list_items.id'], name=op.f('fk_user_object_list_item_dsos_user_object_list_item_id_user_object_list_items')),
    sa.UniqueConstraint('user_object_list_item_id', 'dso_id', name='unique_user_object_list_item_dso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_object_list_item_dsos')
    with op.batch_alter_table('user_object_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_object_list_items_user_object_list_id'))

    op.drop_table('user_object_list_items')
    with op.batch_alter_table('user_object_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_object_lists_title'))

    op.drop_table('user_object_lists')
    # ### end Alembic commands ###
