"""Dso/doublestar list type

Revision ID: 26c28ab1f723
Revises: 4e0e5c99091a
Create Date: 2023-10-28 11:05:51.011564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c28ab1f723'
down_revision = '4e0e5c99091a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_type', sa.Enum('CZSKY', 'CLASSIC', 'TYPED', 'EXOTICS', name='doublestarlisttype'), nullable=True))

    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_type', sa.Enum('CZSKY', 'CLASSIC', 'TYPED', 'EXOTICS', name='dsolisttype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.drop_column('list_type')

    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.drop_column('list_type')

    # ### end Alembic commands ###
