"""is_public in observation

Revision ID: 296321262eb7
Revises: d5ee5b0eb182
Create Date: 2021-08-22 13:35:53.765830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296321262eb7'
down_revision = 'd5ee5b0eb182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
