"""SQM4

Revision ID: 2f58b462eb39
Revises: 25a9ec3ca761
Create Date: 2020-03-05 20:10:34.545964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f58b462eb39'
down_revision = '25a9ec3ca761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sqm_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_sqm_devices_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sqm_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sqm_devices_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
