"""Observation.sqm

Revision ID: 300fea3d8488
Revises: 9c7357f062b6
Create Date: 2021-11-01 22:40:58.489096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300fea3d8488'
down_revision = '9c7357f062b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('sqm')

    # ### end Alembic commands ###
