"""DSO list

Revision ID: 310f98c96a68
Revises: a52cd8d12c31
Create Date: 2020-03-01 15:11:36.751536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310f98c96a68'
down_revision = 'a52cd8d12c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dso_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_dso_lists_create_by_users')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_dso_lists_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dso_lists'))
    )
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dso_lists_name'), ['name'], unique=False)

    op.create_table('dso_list_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dso_list_id', sa.Integer(), nullable=False),
    sa.Column('short_descr', sa.String(length=256), nullable=True),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_dso_list_descriptions_create_by_users')),
    sa.ForeignKeyConstraint(['dso_list_id'], ['dso_lists.id'], name=op.f('fk_dso_list_descriptions_dso_list_id_dso_lists')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_dso_list_descriptions_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dso_list_descriptions'))
    )
    op.create_table('dso_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dso_list_id', sa.Integer(), nullable=False),
    sa.Column('dso_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_dso_list_items_create_by_users')),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name=op.f('fk_dso_list_items_dso_id_deepsky_objects')),
    sa.ForeignKeyConstraint(['dso_list_id'], ['dso_lists.id'], name=op.f('fk_dso_list_items_dso_list_id_dso_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dso_list_items'))
    )
    with op.batch_alter_table('dso_list_items', schema=None) as batch_op:
        batch_op.create_index('dso_list_item_index', ['dso_list_id', 'item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_list_items', schema=None) as batch_op:
        batch_op.drop_index('dso_list_item_index')

    op.drop_table('dso_list_items')
    op.drop_table('dso_list_descriptions')
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dso_lists_name'))

    op.drop_table('dso_lists')
    # ### end Alembic commands ###
