"""Delete observation_plan_run_items

Revision ID: 33e0b77a579f
Revises: 7068344c616b
Create Date: 2021-11-23 20:00:23.341443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e0b77a579f'
down_revision = '7068344c616b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_plan_run_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_plan_run_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('observation_plan_run_id', sa.INTEGER(), nullable=False),
    sa.Column('dso_id', sa.INTEGER(), nullable=True),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name='fk_observation_plan_run_items_dso_id_deepsky_objects'),
    sa.ForeignKeyConstraint(['observation_plan_run_id'], ['observation_plan_runs.id'], name='fk_observation_plan_run_items_observation_plan_run_id_observation_plan_runs'),
    sa.PrimaryKeyConstraint('id', name='pk_observation_plan_run_items')
    )
    # ### end Alembic commands ###
