"""Planets

Revision ID: 34baace6b42d
Revises: 68da8c2b8145
Create Date: 2022-10-16 10:49:55.242717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34baace6b42d'
down_revision = '68da8c2b8145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('int_designation', sa.Integer(), nullable=True),
    sa.Column('iau_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planets'))
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planets_int_designation'), ['int_designation'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planets_int_designation'))

    op.drop_table('planets')
    # ### end Alembic commands ###
