"""Planet in session plan item

Revision ID: 354e4859bfa9
Revises: ac8c3a9c0bec
Create Date: 2022-11-12 10:34:14.642903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354e4859bfa9'
down_revision = 'ac8c3a9c0bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_session_plan_items_planet_id_planets'), 'planets', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_plan_items_planet_id_planets'), type_='foreignkey')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
