"""Default telescope

Revision ID: 380f0a73bbc7
Revises: 73781b19429c
Create Date: 2024-09-24 18:45:32.596822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380f0a73bbc7'
down_revision = '73781b19429c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_telescope_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observing_sessions_default_telescope_id_telescopes'), 'telescopes', ['default_telescope_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observing_sessions_default_telescope_id_telescopes'), type_='foreignkey')
        batch_op.drop_column('default_telescope_id')

    # ### end Alembic commands ###
