"""UserDoubleStarDescription

Revision ID: 3bdc457b5149
Revises: f0756285e3c6
Create Date: 2023-09-30 09:34:25.012175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdc457b5149'
down_revision = 'f0756285e3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_double_star_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_star_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.String(length=2), nullable=True),
    sa.Column('common_name', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('cons_order', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_user_double_star_descriptions_create_by_users')),
    sa.ForeignKeyConstraint(['double_star_id'], ['double_stars.id'], name=op.f('fk_user_double_star_descriptions_double_star_id_double_stars')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_user_double_star_descriptions_update_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_double_star_descriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_double_star_descriptions'))
    )
    with op.batch_alter_table('user_double_star_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_double_star_descriptions_double_star_id'), ['double_star_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_double_star_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_double_star_descriptions_double_star_id'))

    op.drop_table('user_double_star_descriptions')
    # ### end Alembic commands ###
