"""Double star to observation

Revision ID: 3fb39d7f2c94
Revises: b33fdd8d3307
Create Date: 2022-04-09 10:03:31.348612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb39d7f2c94'
down_revision = 'b33fdd8d3307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.Enum('DSO', 'DOUBLE_STAR', name='observationtargettype'), nullable=True))
        batch_op.add_column(sa.Column('double_star_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observations_double_star_id_double_stars'), 'double_stars', ['double_star_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_double_star_id_double_stars'), type_='foreignkey')
        batch_op.drop_column('double_star_id')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
