"""Minor planet current RA/Dec/Constell

Revision ID: 3fca3e3e5eec
Revises: f8cccdc3dde0
Create Date: 2022-10-29 15:24:03.573453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fca3e3e5eec'
down_revision = 'f8cccdc3dde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cur_ra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cur_dec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cur_constell_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_minor_planets_cur_constell_id_constellations'), 'constellations', ['cur_constell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_minor_planets_cur_constell_id_constellations'), type_='foreignkey')
        batch_op.drop_column('cur_constell_id')
        batch_op.drop_column('cur_dec')
        batch_op.drop_column('cur_ra')

    # ### end Alembic commands ###
