"""telescope light_grasp

Revision ID: 427fbd40838b
Revises: d709583089a4
Create Date: 2022-01-01 20:07:12.752768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427fbd40838b'
down_revision = 'd709583089a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_grasp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_column('light_grasp')

    # ### end Alembic commands ###
