"""Dso/doublestar list type2

Revision ID: 441f32a36c11
Revises: 26c28ab1f723
Create Date: 2023-10-28 11:48:18.952613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441f32a36c11'
down_revision = '26c28ab1f723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('star_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_type', sa.Enum('CZSKY', 'CLASSIC', 'TYPED', 'EXOTICS', name='deepskylisttype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('star_lists', schema=None) as batch_op:
        batch_op.drop_column('list_type')

    # ### end Alembic commands ###
