"""Fixed magnification

Revision ID: 46f2aaa1c656
Revises: 782cfc2f9de3
Create Date: 2021-12-30 20:38:48.066663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f2aaa1c656'
down_revision = '782cfc2f9de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_magnification', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_column('fixed_magnification')

    # ### end Alembic commands ###
