"""Index is_active

Revision ID: 4e0e5c99091a
Revises: 3bdc457b5149
Create Date: 2023-10-15 13:07:44.331278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0e5c99091a'
down_revision = '3bdc457b5149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observing_sessions_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observing_sessions_is_active'))

    # ### end Alembic commands ###
