"""Constell in session plan item

Revision ID: 4f33ef5ae1e5
Revises: 3fca3e3e5eec
Create Date: 2022-10-29 16:51:46.971432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f33ef5ae1e5'
down_revision = '3fca3e3e5eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constell_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_session_plan_items_constell_id_constellations'), 'constellations', ['constell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_plan_items_constell_id_constellations'), type_='foreignkey')
        batch_op.drop_column('constell_id')

    # ### end Alembic commands ###
