"""comet minor pl in observed

Revision ID: 52d7cbba3e4f
Revises: 0b1286010134
Create Date: 2024-11-23 16:15:48.471380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d7cbba3e4f'
down_revision = '0b1286010134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', name='observedtargettype'), nullable=True))
        batch_op.add_column(sa.Column('comet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minor_planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observed_list_items_comet_id_comets'), 'comets', ['comet_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_observed_list_items_minor_planet_id_minor_planets'), 'minor_planets', ['minor_planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observed_list_items_minor_planet_id_minor_planets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_observed_list_items_comet_id_comets'), type_='foreignkey')
        batch_op.drop_column('minor_planet_id')
        batch_op.drop_column('comet_id')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
