"""Remove OMD content

Revision ID: 53862c725f8c
Revises: 2559cd21e9dc
Create Date: 2022-01-02 21:15:46.825317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53862c725f8c'
down_revision = '2559cd21e9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_column('omd_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('omd_content', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
