"""SessionPlanItems

Revision ID: 53c4dfab308a
Revises: 0c64976b4e31
Create Date: 2021-03-27 15:23:04.342866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c4dfab308a'
down_revision = '0c64976b4e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_plan_id', sa.Integer(), nullable=False),
    sa.Column('dso_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name=op.f('fk_session_plan_items_dso_id_deepsky_objects')),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plans.id'], name=op.f('fk_session_plan_items_session_plan_id_session_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_plan_items'))
    )
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_plans_sky_list_id_sky_lists', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_session_plans_sky_list_id_sky_lists', 'sky_lists', ['sky_list_id'], ['id'])

    op.drop_table('session_plan_items')
    # ### end Alembic commands ###
