"""Star common_name index

Revision ID: 5408f9f595d3
Revises: d6ccabe47ad7
Create Date: 2021-03-28 16:20:57.521181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5408f9f595d3'
down_revision = 'd6ccabe47ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stars_common_name'), ['common_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stars_common_name'))

    # ### end Alembic commands ###
