"""SQM

Revision ID: 563303b02f78
Revises: 310f98c96a68
Create Date: 2020-03-05 19:21:54.684398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563303b02f78'
down_revision = '310f98c96a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sql_readings')
    op.drop_table('sql_devices')
    op.drop_table('sql_read_values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sql_read_values',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sql_reading_id', sa.INTEGER(), nullable=False),
    sa.Column('sky_position', sa.INTEGER(), nullable=True),
    sa.Column('value_1', sa.FLOAT(), nullable=True),
    sa.Column('value_2', sa.FLOAT(), nullable=True),
    sa.Column('value_3', sa.FLOAT(), nullable=True),
    sa.Column('value_4', sa.FLOAT(), nullable=True),
    sa.Column('value_5', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['sql_reading_id'], ['sql_readings.id'], name='fk_sql_read_values_sql_reading_id_sql_readings'),
    sa.PrimaryKeyConstraint('id', name='pk_sql_read_values')
    )
    op.create_table('sql_devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=1), nullable=True),
    sa.Column('sub_type', sa.VARCHAR(length=16), nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('descr', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_sql_devices')
    )
    op.create_table('sql_readings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sql_device_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('observation_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('weather', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('update_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name='fk_sql_readings_create_by_users'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='fk_sql_readings_location_id_locations'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name='fk_sql_readings_observation_id_observations'),
    sa.ForeignKeyConstraint(['sql_device_id'], ['sql_devices.id'], name='fk_sql_readings_sql_device_id_sql_devices'),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name='fk_sql_readings_update_by_users'),
    sa.PrimaryKeyConstraint('id', name='pk_sql_readings')
    )
    # ### end Alembic commands ###
