"""Revert unique

Revision ID: 5684dbbc94e0
Revises: a54e3bb3adfa
Create Date: 2020-10-09 19:39:32.929558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5684dbbc94e0'
down_revision = 'a54e3bb3adfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dso_lists_name'), ['name'], unique=False)
        batch_op.drop_constraint('uq_dso_lists_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_dso_lists_name', ['name'])
        batch_op.drop_index(batch_op.f('ix_dso_lists_name'))

    # ### end Alembic commands ###
