"""is_public in session_plan

Revision ID: 58e0eb4de5b1
Revises: afe8b7686e9a
Create Date: 2021-04-07 21:25:37.798348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e0eb4de5b1'
down_revision = 'afe8b7686e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
