"""NUllable date_to

Revision ID: 59e984573cf3
Revises: e6d026423ae6
Create Date: 2022-01-07 20:00:56.665008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e984573cf3'
down_revision = 'e6d026423ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
