"""Rename position angle

Revision ID: 5b7407e4ef5c
Revises: fe6655aa09a6
Create Date: 2022-03-19 09:43:21.828967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7407e4ef5c'
down_revision = 'fe6655aa09a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.alter_column('positon_angle', nullable=True, new_column_name='position_angle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.alter_column('position_angle', nullable=True, new_column_name='positon_angle')

    # ### end Alembic commands ###
