"""Normalized designation in double stars

Revision ID: 5daf63794805
Revises: b4a752d2ae5e
Create Date: 2022-01-16 18:36:52.401850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daf63794805'
down_revision = 'b4a752d2ae5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norm_other_designation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.drop_column('norm_other_designation')

    # ### end Alembic commands ###
