"""Add header notes to observation_item

Revision ID: 5dc2704bf6bd
Revises: 33e0b77a579f
Create Date: 2021-11-24 19:35:17.686771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc2704bf6bd'
down_revision = '33e0b77a579f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.drop_column('header_notes')

    # ### end Alembic commands ###
