"""References

Revision ID: 5e6cf999af0a
Revises: 
Create Date: 2020-02-09 11:49:19.762269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6cf999af0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_dso_descriptions', sa.Column('references', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_dso_descriptions', 'references')
    # ### end Alembic commands ###
