"""Remove observation date

Revision ID: 64b7d9e07d0f
Revises: fb74505f790b
Create Date: 2021-12-31 16:46:51.341945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b7d9e07d0f'
down_revision = 'fb74505f790b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('ix_observations_date')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.create_index('ix_observations_date', ['date'], unique=False)

    # ### end Alembic commands ###
