"""Supernovae

Revision ID: 68da8c2b8145
Revises: faad20cc937c
Create Date: 2022-10-06 10:42:03.409742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68da8c2b8145'
down_revision = 'faad20cc937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supernovas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('host_galaxy', sa.String(length=30), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('sn_type', sa.String(length=30), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('offset', sa.String(length=30), nullable=True),
    sa.Column('max_mag', sa.Float(), nullable=True),
    sa.Column('max_mag_date', sa.DateTime(), nullable=True),
    sa.Column('latest_mag', sa.Float(), nullable=True),
    sa.Column('latest_observed', sa.DateTime(), nullable=True),
    sa.Column('first_observed', sa.DateTime(), nullable=True),
    sa.Column('discoverer', sa.String(length=100), nullable=True),
    sa.Column('aka', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], name=op.f('fk_supernovas_constellation_id_constellations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supernovas'))
    )
    with op.batch_alter_table('supernovas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supernovas_designation'), ['designation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supernovas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supernovas_designation'))

    op.drop_table('supernovas')
    # ### end Alembic commands ###
