"""Comet in observ

Revision ID: 6a6729c48b67
Revises: 8cf4d5343ade
Create Date: 2022-05-13 20:30:11.751912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6729c48b67'
down_revision = '8cf4d5343ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_observations_dec'), ['dec'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_ra'), ['ra'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_observations_comet_id_comets'), 'comets', ['comet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_comet_id_comets'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_observations_ra'))
        batch_op.drop_index(batch_op.f('ix_observations_dec'))
        batch_op.drop_column('dec')
        batch_op.drop_column('ra')
        batch_op.drop_column('comet_id')

    # ### end Alembic commands ###
