"""Star in dbl star

Revision ID: 6ed23def7e1a
Revises: f7fbf732ac7e
Create Date: 2022-01-16 12:43:14.449866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed23def7e1a'
down_revision = 'f7fbf732ac7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_double_stars_star_id_stars'), 'stars', ['star_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_double_stars_star_id_stars'), type_='foreignkey')
        batch_op.drop_column('star_id')

    # ### end Alembic commands ###
