"""Double stars

Revision ID: 6ef961045ced
Revises: e9410b3612f4
Create Date: 2022-01-14 22:50:25.133832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef961045ced'
down_revision = 'e9410b3612f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_column('ads')
        batch_op.drop_column('ads_comp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ads_comp', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('ads', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
