"""news lang_code not nullable

Revision ID: 7068344c616b
Revises: c064e129d352
Create Date: 2021-11-13 12:52:57.862756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7068344c616b'
down_revision = 'c064e129d352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('lang_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('lang_code',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
