"""cur_angular_dist_from_sun

Revision ID: 73781b19429c
Revises: 1859df95193b
Create Date: 2024-09-07 10:29:32.605262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73781b19429c'
down_revision = '1859df95193b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cur_angular_dist_from_sun', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.drop_column('cur_angular_dist_from_sun')

    # ### end Alembic commands ###
