"""add last_login and create_date to user

Revision ID: 7cb741ad7234
Revises: 5dc2704bf6bd
Create Date: 2021-12-05 16:27:16.459127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb741ad7234'
down_revision = '5dc2704bf6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
