"""Stars.2

Revision ID: 85735fbf6752
Revises: a58e53077779
Create Date: 2020-02-20 19:34:16.580168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85735fbf6752'
down_revision = 'a58e53077779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stars_sao', table_name='stars')
    op.create_index(op.f('ix_stars_sao'), 'stars', ['sao'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stars_sao'), table_name='stars')
    op.create_index('ix_stars_sao', 'stars', ['sao'], unique=1)
    # ### end Alembic commands ###
