"""change timezone data type4

Revision ID: 86229133e8b5
Revises: 9ebca7fabbb3
Create Date: 2022-01-08 11:27:02.078082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86229133e8b5'
down_revision = '9ebca7fabbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_zone', sa.String(length=64), nullable=True))
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.INTEGER(), nullable=True))
        batch_op.drop_column('time_zone')

    # ### end Alembic commands ###
