"""chart_themes.order

Revision ID: 89924dfb104f
Revises: dd0b2657bc61
Create Date: 2024-11-24 16:23:52.122501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89924dfb104f'
down_revision = 'dd0b2657bc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
