"""created_by_import

Revision ID: 90236885bd74
Revises: 53862c725f8c
Create Date: 2022-01-03 22:08:40.739260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90236885bd74'
down_revision = '53862c725f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_import', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.drop_column('created_by_import')

    # ### end Alembic commands ###
