"""Location position

Revision ID: 9c7357f062b6
Revises: 296321262eb7
Create Date: 2021-09-15 19:02:37.486501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7357f062b6'
down_revision = '296321262eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_position', sa.String(length=256), nullable=True))
        batch_op.drop_column('txt_location_name')

    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_position', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_column('location_position')

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txt_location_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('location_position')

    # ### end Alembic commands ###
