"""Add mag to dso

Revision ID: 9d54e8c4a577
Revises: f6bc1d840c6d
Create Date: 2020-02-16 20:17:32.910201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d54e8c4a577'
down_revision = 'f6bc1d840c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deepsky_objects', sa.Column('mag', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deepsky_objects', 'mag')
    # ### end Alembic commands ###
