"""References

Revision ID: 9e9b0889c82b
Revises: 938b587cee48
Create Date: 2021-01-23 14:06:16.124109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9b0889c82b'
down_revision = '938b587cee48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constellations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_dec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('label_ra', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constellations', schema=None) as batch_op:
        batch_op.drop_column('label_ra')
        batch_op.drop_column('label_dec')

    # ### end Alembic commands ###
