"""long description in dso list

Revision ID: 9f7a380df67c
Revises: 5684dbbc94e0
Create Date: 2020-10-09 23:48:07.883709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7a380df67c'
down_revision = '5684dbbc94e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_list_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_name', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_dso_list_descriptions_long_name'), ['long_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_list_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dso_list_descriptions_long_name'))
        batch_op.drop_column('long_name')

    # ### end Alembic commands ###
