"""News

Revision ID: a01295e9cae9
Revises: 44ded867c11b
Create Date: 2021-04-03 17:28:34.289323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01295e9cae9'
down_revision = '44ded867c11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('ra', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('dso_id', sa.Integer(), nullable=True),
    sa.Column('title_row', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_news_create_by_users')),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name=op.f('fk_news_dso_id_deepsky_objects')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_news_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_dec'), ['dec'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_ra'), ['ra'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_title'))
        batch_op.drop_index(batch_op.f('ix_news_ra'))
        batch_op.drop_index(batch_op.f('ix_news_dec'))

    op.drop_table('news')
    # ### end Alembic commands ###
