"""Remove equipment indexes

Revision ID: a0dbbad0f04d
Revises: 89924dfb104f
Create Date: 2024-12-09 19:22:34.218973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dbbad0f04d'
down_revision = '89924dfb104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.drop_index('ix_eyepieces_model')
        batch_op.drop_index('ix_eyepieces_vendor')

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.drop_index('ix_lenses_model')
        batch_op.drop_index('ix_lenses_vendor')

    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_index('ix_telescopes_model')
        batch_op.drop_index('ix_telescopes_vendor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.create_index('ix_telescopes_vendor', ['vendor'], unique=False)
        batch_op.create_index('ix_telescopes_model', ['model'], unique=False)

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.create_index('ix_lenses_vendor', ['vendor'], unique=False)
        batch_op.create_index('ix_lenses_model', ['model'], unique=False)

    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.create_index('ix_eyepieces_vendor', ['vendor'], unique=False)
        batch_op.create_index('ix_eyepieces_model', ['model'], unique=False)

    # ### end Alembic commands ###
