"""imp_hist_rec_id in equipment

Revision ID: a1294e02f7f4
Revises: 3fb39d7f2c94
Create Date: 2022-04-11 19:58:53.221024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1294e02f7f4'
down_revision = '3fb39d7f2c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_history_rec_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_eyepieces_import_history_rec_id'), ['import_history_rec_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_eyepieces_import_history_rec_id_import_history_recs'), 'import_history_recs', ['import_history_rec_id'], ['id'])

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_history_rec_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_filters_import_history_rec_id'), ['import_history_rec_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_filters_import_history_rec_id_import_history_recs'), 'import_history_recs', ['import_history_rec_id'], ['id'])

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_history_rec_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lenses_import_history_rec_id'), ['import_history_rec_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_lenses_import_history_rec_id_import_history_recs'), 'import_history_recs', ['import_history_rec_id'], ['id'])

    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_history_rec_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_telescopes_import_history_rec_id'), ['import_history_rec_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_telescopes_import_history_rec_id_import_history_recs'), 'import_history_recs', ['import_history_rec_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_telescopes_import_history_rec_id_import_history_recs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_telescopes_import_history_rec_id'))
        batch_op.drop_column('import_history_rec_id')

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lenses_import_history_rec_id_import_history_recs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lenses_import_history_rec_id'))
        batch_op.drop_column('import_history_rec_id')

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_filters_import_history_rec_id_import_history_recs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_filters_import_history_rec_id'))
        batch_op.drop_column('import_history_rec_id')

    with op.batch_alter_table('eyepieces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_eyepieces_import_history_rec_id_import_history_recs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_eyepieces_import_history_rec_id'))
        batch_op.drop_column('import_history_rec_id')

    # ### end Alembic commands ###
