"""Comet observation

Revision ID: a1d3550dfe97
Revises: ade001aad88b
Create Date: 2022-09-01 07:21:37.842089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d3550dfe97'
down_revision = 'ade001aad88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comet_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comet_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('mag', sa.Float(), nullable=True),
    sa.Column('coma_diameter', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comet_id'], ['comets.id'], name=op.f('fk_comet_observations_comet_id_comets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comet_observations'))
    )
    with op.batch_alter_table('comet_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comet_observations_comet_id'), ['comet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comet_observations_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comet_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comet_observations_date'))
        batch_op.drop_index(batch_op.f('ix_comet_observations_comet_id'))

    op.drop_table('comet_observations')
    # ### end Alembic commands ###
