"""dsolist long names

Revision ID: a54e3bb3adfa
Revises: 006cee50cac0
Create Date: 2020-10-09 19:13:33.230918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54e3bb3adfa'
down_revision = '006cee50cac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_name', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_dso_lists_long_name'), ['long_name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_dso_lists_name'), ['name'])
        batch_op.drop_index('ix_dso_lists_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.create_index('ix_dso_lists_name', ['name'], unique=False)
        batch_op.drop_constraint(batch_op.f('uq_dso_lists_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_dso_lists_long_name'))
        batch_op.drop_column('long_name')

    # ### end Alembic commands ###
