"""DSO distance

Revision ID: a58530607d43
Revises: b241f210b112
Create Date: 2022-09-09 18:50:21.797271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58530607d43'
down_revision = 'b241f210b112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
