"""Minor planet mag

Revision ID: ac8c3a9c0bec
Revises: ebddffa4cf16
Create Date: 2022-10-31 19:41:53.248834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8c3a9c0bec'
down_revision = 'ebddffa4cf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eval_mag', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.drop_column('eval_mag')

    # ### end Alembic commands ###
