"""import_source

Revision ID: ade001aad88b
Revises: 23ada8e1fa92
Create Date: 2022-08-16 22:23:02.042165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade001aad88b'
down_revision = '23ada8e1fa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_source', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deepsky_objects', schema=None) as batch_op:
        batch_op.drop_column('import_source')

    # ### end Alembic commands ###
