"""News fixes

Revision ID: afe8b7686e9a
Revises: 3266d893fa99
Create Date: 2021-04-03 19:38:07.591074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe8b7686e9a'
down_revision = '3266d893fa99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_dso_id_deepsky_objects', type_='foreignkey')
        batch_op.drop_column('dso_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dso_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_news_dso_id_deepsky_objects', 'deepsky_objects', ['dso_id'], ['id'])

    # ### end Alembic commands ###
