"""Comets' actual positions

Revision ID: b241f210b112
Revises: 087f708b28ab
Create Date: 2022-09-03 13:44:57.424502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b241f210b112'
down_revision = '087f708b28ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cur_ra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cur_dec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cur_constell_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comets_cur_constell_id_constellations'), 'constellations', ['cur_constell_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comets_cur_constell_id_constellations'), type_='foreignkey')
        batch_op.drop_column('cur_constell_id')
        batch_op.drop_column('cur_dec')
        batch_op.drop_column('cur_ra')

    # ### end Alembic commands ###
