"""Unique constraint in observation_dsos

Revision ID: b33fdd8d3307
Revises: 0e9cb1f10c33
Create Date: 2022-04-06 20:27:09.445663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33fdd8d3307'
down_revision = '0e9cb1f10c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_dsos', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_observation_dso', ['observation_id', 'dso_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_dsos', schema=None) as batch_op:
        batch_op.drop_constraint('unique_observation_dso', type_='unique')

    # ### end Alembic commands ###
