"""Minor planets

Revision ID: b575afc826ce
Revises: 67bca0be2155
Create Date: 2022-01-26 21:15:34.656136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b575afc826ce'
down_revision = '67bca0be2155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('int_designation', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_minor_planets_int_designation'), ['int_designation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minor_planets_int_designation'))
        batch_op.drop_column('int_designation')

    # ### end Alembic commands ###
