"""observation_item.lens_id

Revision ID: ba977499e5a3
Revises: 427fbd40838b
Create Date: 2022-01-01 20:09:16.509570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba977499e5a3'
down_revision = '427fbd40838b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lens_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observation_items_lens_id_lenses'), 'lenses', ['lens_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observation_items_lens_id_lenses'), type_='foreignkey')
        batch_op.drop_column('lens_id')

    # ### end Alembic commands ###
