"""Remove skylist from SessionPlan

Revision ID: c169dc12d5eb
Revises: 5408f9f595d3
Create Date: 2021-03-28 20:44:51.564160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c169dc12d5eb'
down_revision = '5408f9f595d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_column('sky_list_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sky_list_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
