"""Planet moons2

Revision ID: d08214aac36a
Revises: 0ca6794f5ed5
Create Date: 2024-10-12 21:51:08.644907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08214aac36a'
down_revision = '0ca6794f5ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet_moons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planet_moons_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet_moons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planet_moons_name'))

    # ### end Alembic commands ###
