"""Star refactor

Revision ID: d6ccabe47ad7
Revises: 53c4dfab308a
Create Date: 2021-03-28 16:16:32.555391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ccabe47ad7'
down_revision = '53c4dfab308a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bayer', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('common_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('flamsteed', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_stars_bayer'), ['bayer'], unique=False)
        batch_op.create_index(batch_op.f('ix_stars_flamsteed'), ['flamsteed'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_stars_fk5'), ['fk5'])
        batch_op.drop_index('ix_stars_bayer_flamsteed')
        batch_op.drop_index('ix_stars_fk5')
        batch_op.drop_column('bayer_flamsteed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bayer_flamsteed', sa.VARCHAR(length=10), nullable=True))
        batch_op.create_index('ix_stars_fk5', ['fk5'], unique=1)
        batch_op.create_index('ix_stars_bayer_flamsteed', ['bayer_flamsteed'], unique=False)
        batch_op.drop_constraint(batch_op.f('uq_stars_fk5'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_stars_flamsteed'))
        batch_op.drop_index(batch_op.f('ix_stars_bayer'))
        batch_op.drop_column('flamsteed')
        batch_op.drop_column('common_name')
        batch_op.drop_column('bayer')

    # ### end Alembic commands ###
