"""Lenses

Revision ID: d709583089a4
Revises: 64b7d9e07d0f
Create Date: 2022-01-01 17:21:06.224154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd709583089a4'
down_revision = '64b7d9e07d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('lens_type', sa.Enum('BARLOW', 'COMA_CORRECTOR', 'OTHER', name='lenstype'), nullable=True),
    sa.Column('magnification', sa.Float(), nullable=False),
    sa.Column('diameter_inch', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_lenses_create_by_users')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_lenses_update_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lenses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lenses'))
    )
    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lenses_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_lenses_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_lenses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lenses_vendor'), ['vendor'], unique=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('iau_code', sa.Integer(), nullable=True))

    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telescope_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('eyepiece_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accessories', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('filter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('magnification', sa.Float(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observation_items_filter_id_filters'), 'filters', ['filter_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_observation_items_telescope_id_telescopes'), 'telescopes', ['telescope_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_observation_items_eyepiece_id_eyepieces'), 'eyepieces', ['eyepiece_id'], ['id'])
        batch_op.drop_column('header_notes')

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faintest_star', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('equipment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('equipment')
        batch_op.drop_column('weather')
        batch_op.drop_column('faintest_star')

    with op.batch_alter_table('observation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_notes', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_observation_items_eyepiece_id_eyepieces'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_observation_items_telescope_id_telescopes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_observation_items_filter_id_filters'), type_='foreignkey')
        batch_op.drop_column('magnification')
        batch_op.drop_column('filter_id')
        batch_op.drop_column('accessories')
        batch_op.drop_column('eyepiece_id')
        batch_op.drop_column('telescope_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('iau_code')
        batch_op.drop_column('timezone')

    with op.batch_alter_table('lenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lenses_vendor'))
        batch_op.drop_index(batch_op.f('ix_lenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_lenses_name'))
        batch_op.drop_index(batch_op.f('ix_lenses_model'))

    op.drop_table('lenses')
    # ### end Alembic commands ###
