"""Double star list

Revision ID: d9babf3a822a
Revises: cadeea9b1c48
Create Date: 2022-07-23 11:06:19.735061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9babf3a822a'
down_revision = 'cadeea9b1c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_star_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('long_name', sa.String(length=256), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_lists_create_by_users')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_double_star_lists_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_lists'))
    )
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_star_lists_long_name'), ['long_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_double_star_lists_name'), ['name'], unique=False)

    op.create_table('double_star_list_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_star_list_id', sa.Integer(), nullable=False),
    sa.Column('long_name', sa.String(length=256), nullable=True),
    sa.Column('short_descr', sa.String(length=256), nullable=True),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_list_descriptions_create_by_users')),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name=op.f('fk_double_star_list_descriptions_double_star_list_id_double_star_lists')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_double_star_list_descriptions_update_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_list_descriptions'))
    )
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_star_list_descriptions_long_name'), ['long_name'], unique=False)

    op.create_table('double_star_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_star_list_id', sa.Integer(), nullable=False),
    sa.Column('double_star_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_double_star_list_items_create_by_users')),
    sa.ForeignKeyConstraint(['double_star_id'], ['double_stars.id'], name=op.f('fk_double_star_list_items_double_star_id_double_stars')),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name=op.f('fk_double_star_list_items_double_star_list_id_double_star_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_star_list_items'))
    )
    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.create_index('double_star_list_item_index', ['double_star_list_id', 'item_id'], unique=False)

    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('double_star_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observed_list_items_double_star_id_double_stars'), 'double_stars', ['double_star_id'], ['id'])

    with op.batch_alter_table('wish_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('double_star_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_wish_list_items_double_star_id_double_stars'), 'double_stars', ['double_star_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_wish_list_items_double_star_id_double_stars'), type_='foreignkey')
        batch_op.drop_column('double_star_id')

    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observed_list_items_double_star_id_double_stars'), type_='foreignkey')
        batch_op.drop_column('double_star_id')

    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.drop_index('double_star_list_item_index')

    op.drop_table('double_star_list_items')
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_star_list_descriptions_long_name'))

    op.drop_table('double_star_list_descriptions')
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_star_lists_name'))
        batch_op.drop_index(batch_op.f('ix_double_star_lists_long_name'))

    op.drop_table('double_star_lists')
    # ### end Alembic commands ###
