"""seeing+transparency

Revision ID: dccf7f7d1c9b
Revises: 300fea3d8488
Create Date: 2021-11-03 19:26:05.689657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccf7f7d1c9b'
down_revision = '300fea3d8488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeing', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('transparency', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('transparency')
        batch_op.drop_column('seeing')

    # ### end Alembic commands ###
