"""Custom chart themes

Revision ID: dd0b2657bc61
Revises: 52d7cbba3e4f
Create Date: 2024-11-24 11:20:45.819015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0b2657bc61'
down_revision = '52d7cbba3e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_type', sa.Enum('DARK', 'LIGHT', 'NIGHT', name='defaultthemetype'), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('fk_chart_themes_create_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_chart_themes_update_by_users', type_='foreignkey')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_chart_themes_update_by_users', 'users', ['update_by'], ['id'])
        batch_op.create_foreign_key('fk_chart_themes_create_by_users', 'users', ['create_by'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('default_type')

    # ### end Alembic commands ###
