"""WishList refactor

Revision ID: dd8d565e95d9
Revises: 9f7a380df67c
Create Date: 2020-10-10 18:29:22.649865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8d565e95d9'
down_revision = '9f7a380df67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_list_id', sa.Integer(), nullable=False),
    sa.Column('dso_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dso_id'], ['deepsky_objects.id'], name=op.f('fk_wish_list_items_dso_id_deepsky_objects')),
    sa.ForeignKeyConstraint(['wish_list_id'], ['wish_lists.id'], name=op.f('fk_wish_list_items_wish_list_id_wish_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wish_list_items'))
    )
    with op.batch_alter_table('wish_lists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wish_lists_update_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_wish_lists_sky_list_id_sky_lists', type_='foreignkey')
        batch_op.drop_constraint('fk_wish_lists_create_by_users', type_='foreignkey')
        batch_op.drop_column('update_by')
        batch_op.drop_column('sky_list_id')
        batch_op.drop_column('create_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sky_list_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('update_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_wish_lists_create_by_users', 'users', ['create_by'], ['id'])
        batch_op.create_foreign_key('fk_wish_lists_sky_list_id_sky_lists', 'sky_lists', ['sky_list_id'], ['id'])
        batch_op.create_foreign_key('fk_wish_lists_update_by_users', 'users', ['update_by'], ['id'])

    op.drop_table('wish_list_items')
    # ### end Alembic commands ###
