"""Observing session is_finished

Revision ID: e1a24e18c48f
Revises: fcb164bca241
Create Date: 2023-07-06 13:06:14.493523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a24e18c48f'
down_revision = 'fcb164bca241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sqm_records', schema=None) as batch_op:
        batch_op.drop_index('sqm_record_index')

    op.drop_table('sqm_records')
    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('long_name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.alter_column('filter_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('UHC', 'OIII', 'CLS', 'HBETA', 'HALPHA', 'COLOR', 'NEUTRAL', 'CORRECTIVE', 'SOLAR', 'BROAD_BAND', 'NARROW_BAND', 'OTHER', name='filtertype'),
               existing_nullable=True)

    with op.batch_alter_table('import_history_recs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PROCESSING', 'IMPORTED', 'DELETED', name='importhistoryrecstatus'),
               existing_nullable=True)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', 'PLANET', name='observationtargettype'),
               existing_nullable=True)

    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=True))
        batch_op.alter_column('seeing',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('TERRIBLE', 'VERYBAD', 'BAD', 'AVERAGE', 'GOOD', 'EXCELLENT', name='seeing'),
               existing_nullable=True)
        batch_op.alter_column('transparency',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('UNUSUAL', 'VERYBAD', 'BAD', 'AVERAGE', 'GOOD', 'EXCELLENT', name='transparency'),
               existing_nullable=True)

    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.alter_column('telescope_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('NAKED_EYE', 'BINOCULAR', 'NEWTON', 'REFRACTOR', 'CASSEGRAIN', 'SCHMIDT_CASSEGRAIN', 'MAKSUTOV', 'KUTTER', 'OTHER', name='telescopetype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telescopes', schema=None) as batch_op:
        batch_op.alter_column('telescope_type',
               existing_type=sa.Enum('NAKED_EYE', 'BINOCULAR', 'NEWTON', 'REFRACTOR', 'CASSEGRAIN', 'SCHMIDT_CASSEGRAIN', 'MAKSUTOV', 'KUTTER', 'OTHER', name='telescopetype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('observing_sessions', schema=None) as batch_op:
        batch_op.alter_column('transparency',
               existing_type=sa.Enum('UNUSUAL', 'VERYBAD', 'BAD', 'AVERAGE', 'GOOD', 'EXCELLENT', name='transparency'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('seeing',
               existing_type=sa.Enum('TERRIBLE', 'VERYBAD', 'BAD', 'AVERAGE', 'GOOD', 'EXCELLENT', name='seeing'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.drop_column('is_finished')

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.alter_column('target_type',
               existing_type=sa.Enum('DSO', 'DBL_STAR', 'COMET', 'M_PLANET', 'PLANET', name='observationtargettype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('import_history_recs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PROCESSING', 'IMPORTED', 'DELETED', name='importhistoryrecstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)

    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.alter_column('filter_type',
               existing_type=sa.Enum('UHC', 'OIII', 'CLS', 'HBETA', 'HALPHA', 'COLOR', 'NEUTRAL', 'CORRECTIVE', 'SOLAR', 'BROAD_BAND', 'NARROW_BAND', 'OTHER', name='filtertype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('dso_lists', schema=None) as batch_op:
        batch_op.alter_column('long_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    op.create_table('sqm_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sqm_device_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_sqm_records')
    )
    with op.batch_alter_table('sqm_records', schema=None) as batch_op:
        batch_op.create_index('sqm_record_index', ['sqm_device_id', 'date_time'], unique=False)

    # ### end Alembic commands ###
