"""DoubleStars2

Revision ID: e4af7a761f21
Revises: 6ef961045ced
Create Date: 2022-01-14 22:54:42.391887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4af7a761f21'
down_revision = '6ef961045ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wds_number', sa.String(length=10), nullable=True),
    sa.Column('common_cat_id', sa.String(length=20), nullable=True),
    sa.Column('components', sa.String(length=12), nullable=True),
    sa.Column('other_designation', sa.Text(), nullable=True),
    sa.Column('pos_angle', sa.Integer(), nullable=True),
    sa.Column('separation', sa.Float(), nullable=True),
    sa.Column('mag_first', sa.Float(), nullable=True),
    sa.Column('mag_second', sa.Float(), nullable=True),
    sa.Column('spectral_type', sa.String(length=20), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('ra_first', sa.Float(), nullable=True),
    sa.Column('dec_first', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellations.id'], name=op.f('fk_double_stars_constellation_id_constellations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_double_stars'))
    )
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_stars_common_cat_id'), ['common_cat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_double_stars_wds_number'), ['wds_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_stars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_stars_wds_number'))
        batch_op.drop_index(batch_op.f('ix_double_stars_common_cat_id'))

    op.drop_table('double_stars')
    # ### end Alembic commands ###
