"""Add from/to to observation

Revision ID: e6d026423ae6
Revises: e893c56f5801
Create Date: 2022-01-07 19:41:25.638012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d026423ae6'
down_revision = 'e893c56f5801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_to', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_observations_date_from'), ['date_from'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_date_from'))
        batch_op.drop_column('date_to')
        batch_op.drop_column('date_from')

    # ### end Alembic commands ###
