"""remove txt_deepsky_object

Revision ID: e893c56f5801
Revises: 90236885bd74
Create Date: 2022-01-05 20:49:23.874326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e893c56f5801'
down_revision = '90236885bd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_column('txt_deepsky_objects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txt_deepsky_objects', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
