"""Src catalogu

Revision ID: e9410b3612f4
Revises: c345e6d15510
Create Date: 2022-01-11 18:18:26.242127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9410b3612f4'
down_revision = 'c345e6d15510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_catalogue', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stars', schema=None) as batch_op:
        batch_op.drop_column('src_catalogue')

    # ### end Alembic commands ###
