"""Comet mags

Revision ID: ebddffa4cf16
Revises: 0818dbd968b3
Create Date: 2022-10-30 09:54:09.784164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebddffa4cf16'
down_revision = '0818dbd968b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mag', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('real_mag', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('real_coma_diameter', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comets_comet_id'), ['comet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comets_cur_constell_id'), ['cur_constell_id'], unique=False)

    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_minor_planets_cur_constell_id'), ['cur_constell_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minor_planets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minor_planets_cur_constell_id'))

    with op.batch_alter_table('comets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comets_cur_constell_id'))
        batch_op.drop_index(batch_op.f('ix_comets_comet_id'))
        batch_op.drop_column('real_coma_diameter')
        batch_op.drop_column('real_mag')
        batch_op.drop_column('mag')

    # ### end Alembic commands ###
