"""Create/Update in observation

Revision ID: ecbd06421e95
Revises: 19c33ee21175
Create Date: 2022-04-02 18:48:15.919409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbd06421e95'
down_revision = '19c33ee21175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('update_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_observations_create_by_users'), 'users', ['create_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_observations_update_by_users'), 'users', ['update_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_update_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_observations_create_by_users'), type_='foreignkey')
        batch_op.drop_column('update_date')
        batch_op.drop_column('create_date')
        batch_op.drop_column('update_by')
        batch_op.drop_column('create_by')

    # ### end Alembic commands ###
