"""Standalone observations

Revision ID: f41cb289d440
Revises: 67605849a3a7
Create Date: 2022-03-31 19:29:50.736067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41cb289d440'
down_revision = '67605849a3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_observations_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_observations_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_observations_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_observations_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
