"""Remove title+notes from skylist

Revision ID: f6bc1d840c6d
Revises: 01a6a04187e8
Create Date: 2020-02-15 15:55:39.378504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bc1d840c6d'
down_revision = '01a6a04187e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_lists', 'title')
    op.drop_column('wish_lists', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_lists', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('wish_lists', sa.Column('title', sa.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
