"""Remove dbl star list

Revision ID: f7fbf732ac7e
Revises: 1416c260ee7e
Create Date: 2022-01-15 23:26:22.932714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fbf732ac7e'
down_revision = '1416c260ee7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_double_star_lists_long_name')
        batch_op.drop_index('ix_double_star_lists_name')

    op.drop_table('double_star_lists')
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_double_star_list_descriptions_long_name')

    op.drop_table('double_star_list_descriptions')
    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.drop_index('double_star_list_item_index')

    op.drop_table('double_star_list_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_star_list_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('double_star_list_id', sa.INTEGER(), nullable=False),
    sa.Column('star_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name='fk_double_star_list_items_create_by_users'),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name='fk_double_star_list_items_double_star_list_id_double_star_lists'),
    sa.ForeignKeyConstraint(['star_id'], ['stars.id'], name='fk_double_star_list_items_star_id_stars'),
    sa.PrimaryKeyConstraint('id', name='pk_double_star_list_items')
    )
    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.create_index('double_star_list_item_index', ['double_star_list_id', 'item_id'], unique=False)

    op.create_table('double_star_list_descriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('double_star_list_id', sa.INTEGER(), nullable=False),
    sa.Column('long_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('short_descr', sa.VARCHAR(length=256), nullable=True),
    sa.Column('lang_code', sa.VARCHAR(length=2), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('update_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name='fk_double_star_list_descriptions_create_by_users'),
    sa.ForeignKeyConstraint(['double_star_list_id'], ['double_star_lists.id'], name='fk_double_star_list_descriptions_double_star_list_id_double_star_lists'),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name='fk_double_star_list_descriptions_update_by_users'),
    sa.PrimaryKeyConstraint('id', name='pk_double_star_list_descriptions')
    )
    with op.batch_alter_table('double_star_list_descriptions', schema=None) as batch_op:
        batch_op.create_index('ix_double_star_list_descriptions_long_name', ['long_name'], unique=False)

    op.create_table('double_star_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('long_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('create_by', sa.INTEGER(), nullable=True),
    sa.Column('update_by', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name='fk_double_star_lists_create_by_users'),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name='fk_double_star_lists_update_by_users'),
    sa.PrimaryKeyConstraint('id', name='pk_double_star_lists')
    )
    with op.batch_alter_table('double_star_lists', schema=None) as batch_op:
        batch_op.create_index('ix_double_star_lists_name', ['name'], unique=False)
        batch_op.create_index('ix_double_star_lists_long_name', ['long_name'], unique=False)

    # ### end Alembic commands ###
