"""Ra Dec in session plan

Revision ID: f8cccdc3dde0
Revises: 54302dfea32f
Create Date: 2022-10-29 09:19:22.190074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cccdc3dde0'
down_revision = '54302dfea32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_session_plan_items_dec'), ['dec'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_plan_items_ra'), ['ra'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_plan_items_ra'))
        batch_op.drop_index(batch_op.f('ix_session_plan_items_dec'))
        batch_op.drop_column('dec')
        batch_op.drop_column('ra')

    # ### end Alembic commands ###
