"""Add missing indexes

Revision ID: faad20cc937c
Revises: de0f323377b3
Create Date: 2022-09-25 08:01:57.124225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faad20cc937c'
down_revision = 'de0f323377b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_double_star_list_items_double_star_list_id'), ['double_star_list_id'], unique=False)

    with op.batch_alter_table('dso_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dso_list_items_dso_list_id'), ['dso_list_id'], unique=False)

    with op.batch_alter_table('obs_session_plan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obs_session_plan_runs_observing_session_id'), ['observing_session_id'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_observing_session_id'), ['observing_session_id'], unique=False)

    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observed_list_items_observed_list_id'), ['observed_list_id'], unique=False)

    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_plan_items_session_plan_id'), ['session_plan_id'], unique=False)

    with op.batch_alter_table('star_list_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_star_list_descriptions_star_list_id'), ['star_list_id'], unique=False)

    with op.batch_alter_table('star_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_star_list_items_star_list_id'), ['star_list_id'], unique=False)

    with op.batch_alter_table('user_star_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_star_descriptions_star_id'), ['star_id'], unique=False)

    with op.batch_alter_table('wish_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wish_list_items_wish_list_id'), ['wish_list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wish_list_items_wish_list_id'))

    with op.batch_alter_table('user_star_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_star_descriptions_star_id'))

    with op.batch_alter_table('star_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_star_list_items_star_list_id'))

    with op.batch_alter_table('star_list_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_star_list_descriptions_star_list_id'))

    with op.batch_alter_table('session_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_plan_items_session_plan_id'))

    with op.batch_alter_table('observed_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observed_list_items_observed_list_id'))

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_observing_session_id'))

    with op.batch_alter_table('obs_session_plan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obs_session_plan_runs_observing_session_id'))

    with op.batch_alter_table('dso_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dso_list_items_dso_list_id'))

    with op.batch_alter_table('double_star_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_double_star_list_items_double_star_list_id'))

    # ### end Alembic commands ###
