"""Observation from-to

Revision ID: fb74505f790b
Revises: 46f2aaa1c656
Create Date: 2021-12-31 15:21:08.586687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb74505f790b'
down_revision = '46f2aaa1c656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_to', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_observations_date_from'), ['date_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_date_to'), ['date_to'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_date_to'))
        batch_op.drop_index(batch_op.f('ix_observations_date_from'))
        batch_op.drop_column('date_to')
        batch_op.drop_column('date_from')

    # ### end Alembic commands ###
