"""Chart theme

Revision ID: fcb164bca241
Revises: 354e4859bfa9
Create Date: 2022-12-03 18:45:00.548967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb164bca241'
down_revision = '354e4859bfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], name=op.f('fk_chart_themes_create_by_users')),
    sa.ForeignKeyConstraint(['update_by'], ['users.id'], name=op.f('fk_chart_themes_update_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chart_themes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chart_themes'))
    )
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_themes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_themes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_themes_user_id'))
        batch_op.drop_index(batch_op.f('ix_chart_themes_name'))

    op.drop_table('chart_themes')
    # ### end Alembic commands ###
