from .observation_views import main_observation
from .standalone_observation_views import main_standalone_observation
from .observing_session_views import main_observing_session
from .observed_views import main_observed
